name: condaenv
channels:
  - conda-forge
dependencies:
  - python==3.11
  - dm-tree
  - netcdf4
  - xarray
  - cartopy
  - jupyterlab
  - boto3
  - nceplibs-g2c
  - grib2io
  - pip
  - uwtools
  - pip:
    - git+https://github.com/noaa-emc/graphcast@aea0678cfbd7e866e4a1d364b456861d0a03954b
    - flax
