#!/usr/bin/env -S bash -euo pipefail

# Export CONDADIR to specify alternate conda install path.
# Export DEVMODE to install development packages.

# Tools:

bootstrap() {
  local condadir env rootdir
  msg Starting
  condadir=$(condadir)
  env=$(env)
  rootdir=$(rootdir)
  if [[ -d $condadir ]]; then
    msg Using existing conda $condadir
  else
    msg Installing conda to $condadir
    (
      os=$(uname)
      test $os == Darwin && os=MacOSX
      machine=$(uname -m)
      installer=Miniforge3-$os-$machine.sh
      version=26.3.2-3
      curl -sSLO https://github.com/conda-forge/miniforge/releases/download/$version/$installer
      bash $installer -bfp $condadir
      rm -v $installer
    )
  fi
  activate
  export PIP_VERBOSE=1
  if [[ -d $condadir/envs/$env ]]; then
    msg Using existing environment $env
  else
    msg Creating environment $env
    conda env create --file $(envyaml) --quiet --yes
  fi
  if [[ -v DEVMODE ]]; then
    msg Installing dev packages into environment $env
    conda env update --file $(dirname $(envyaml))/devpkgs.yaml --name $env --quiet
  fi
  msg Ready
}

docs() {
  local rootdir
  rootdir=$(rootdir)
  activate $(env)
  pdoc --output-dir $rootdir/docs/api $rootdir/drivers
}

format() {
  test $# -eq 0 && echo "usage: $(basename $0) path [path ...]" && exit 1
  msg Formatting code
  activate $(env)
  ruff format $@
  msg Sorting imports
  ruff check --select I --fix $@
  msg Formatting JSON
  for f in $(find $@ -not -path "*/.*" -type f -name "*.json" -o -name "*.jsonschema"); do
    jq -S . $f >$f.new || (echo "    in $f" && rm $f.new && false)
    cmp --quiet $f.new $f && rm $f.new || mv $f.new $f
  done
}

lint() {
  activate $(env)
  ruff check $(rootdir)
}

msg() {
  echo "=> $@"
}

rmenv() {
  activate
  conda env remove -y -n $(env)
}

typecheck() {
  activate $(env)
  mypy $@
}

unittest() {
  activate $(env)
  pytest --cov $(rootdir)/tests
}

# Helpers:

activate() {
  local env
  test -v 1 && env=$1 || env=base
  . $(condadir)/etc/profile.d/conda.sh
  conda activate $env
}

condadir() {
  echo ${CONDADIR:-$(rootdir)/conda}
}

env() {
  sed -n '/^name:.*/ s/^name: *//p' $(envyaml)
}

envyaml() {
  echo $(rootdir)/envs/environment.yaml
}

rootdir() {
  git rev-parse --show-toplevel
}

# Main entrypoint:

test $# -eq 0 && echo "usage: $(basename $0) tool [args ...]" && exit 1
tool=$1
shift
$tool $@
