name: aigfs
channels:
  - conda-forge
  - ufs-community
dependencies:
  - grib2io 2.6.*
  - netcdf4 1.7.*
  - pip
  - pydantic 2.11.*
  - python 3.11.*
  - uwtools 2.19.*
  - wgrib2 3.8.*
  - xarray 2025.10.*
  - pip:
      - git+https://github.com/noaa-emc/graphcast@aea0678cfbd7e866e4a1d364b456861d0a03954b
