ecflow:
  suitedef:
    scheduler: '{{ app.platform.scheduler.type }}'
    suite_retro:
      vars:
        APPDIR: '{{ app.home }}'
        CONFIG: '{{ app.rundir}}/aigfs.yaml'
        ECF_HOME: '{{ app.rundir }}/ecf'
        ECF_INCLUDE: '{{ app.home }}/include'
        ECF_JOB_CMD: 'sbatch -o %ECF_JOBOUT% %ECF_JOB%'
        PLATFORM: '{{ app.platform.name }}'
      family_datetimes:
        repeat_datetime:
          variable: CYCLE
          start: '{{ app.first_cycle.strftime("%Y%m%dT%H%M%S") }}'
          end: '{{ app.last_cycle.strftime("%Y%m%dT%H%M%S") }}'
          step: '{% set f = app.cycle_freq.total_seconds() %}{{ "%02d:%02d:%02d" % (f // 3600, (f % 3600) / 60, f % 60 ) }}'
        family_forecast:
          task_prep:
            script: &script
              includes:
                entry:
                  - <head.h>
                exit:
                  - <tail.h>
              manual: Prepares AIGFS ICS from GFS.
              batchargs: !dict '{{ prep.aigfs_ics.execution.batchargs }}'
              body: |
                source %APPDIR%/bin/activate-%PLATFORM%
                uw execute \
                  --module aigfs.drivers.ics \
                  --classname AIGFSICs \
                  --task run \
                  --config %CONFIG% \
                  --cycle $ISOCYCLE \
                  --key-path prep
          task_forecast:
            trigger: prep == complete
            script:
              <<: *script
              manual: Runs AIGFS forecast.
              batchargs: !dict '{{ forecast.aigfs_inference.execution.batchargs }}'
              body: |
                source %APPDIR%/bin/activate-%PLATFORM%
                uw execute \
                  --module aigfs.drivers.inference \
                  --classname AIGFSInference \
                  --task run \
                  --config %CONFIG% \
                  --cycle $ISOCYCLE \
                  --key-path forecast
          family_post:
            tasks_post_{{ ec.fhr }}:
              expand:
                fhr: !list '[{% for h in range(0, forecast.aigfs_inference.forecast_length + 1, forecast.aigfs_inference.forecast_freq) %}{{ "f%03d" % h }},{% endfor %} ]'
              trigger: '../forecast == complete'
              script:
                <<: *script
                manual: Runs AIGFS post for {{ ec.fhr }}.
                batchargs: !dict '{{ post.aigfs_post.execution.batchargs }}'
                body: |
                  source %APPDIR%/bin/activate-%PLATFORM%
                  export FHR=%FHR%
                  uw execute \
                    --module aigfs.drivers.post \
                    --classname AIGFSPost \
                    --task run \
                    --config %CONFIG% \
                    --cycle $ISOCYCLE \
                    --key-path post \
                    --leadtime %FHR%
              vars:
                FHR: '{{ ec.fhr[1:] }}'
