ecflow:
  suitedef:
    scheduler: "{{ platform.scheduler }}"
    vars:
      AIGFS_APP: "{{ app.home }}"
      ECF_INCLUDE: "{{ app.home }}/include"
      CONFIG: "{{ app.rundir}}/aigfs.yaml"
      PLATFORM: "{{ app.platform }}"
    suite_retro:
      family_datetimes:
        repeat_datetime:
          variable: CYCLE
          start: '{{ app.first_cycle.strftime("%Y%m%dT%H%M%S") }}'
          end: '{{ app.last_cycle.strftime("%Y%m%dT%H%M%S") }}'
          step: '{% set f = app.cycle_freq.total_seconds() %}{{ "%02d:%02d:%02d" % (f // 3600, (f % 3600) / 60, f % 60 ) }}'
        family_forecast:
          task_jaigfs_prep:
            script: &script
              includes:
                entry:
                  - head.h
                  - envir-1.h
                exit:
                  - tail.h
              manual: "Prepares AIGFS ICS from GFS."
              batchargs: !dict "{{ prep.aigfs_ics.execution.batchargs }}"
              body: |
                source %AIGFS_APP%/bin/activate-%PLATFORM%
                uw execute \
                  --module aigfs.drivers.ics \
                  --classname AIGFSICs \
                  --task run \
                  --config %CONFIG% \
                  --cycle $ISOCYCLE \
                  --key-path prep
          task_jaigfs_forecast:
            trigger: jaigfs_prep == complete
            events: !list '[{% for h in range(0, forecast.aigfs_inference.forecast_length + 1, forecast.aigfs_inference.forecast_freq) %}{{ "release_f%03d" % h }},{% endfor %} ]'
            script:
              <<: *script
              manual: "Runs AIGFS forecast."
              batchargs: !dict "{{ forecast.aigfs_inference.execution.batchargs }}"
              body: |
                source %AIGFS_APP%/bin/activate-%PLATFORM%
                uw execute \
                  --module aigfs.drivers.inference \
                  --classname AIGFSInference \
                  --task run \
                  --config %CONFIG% \
                  --cycle $ISOCYCLE \
                  --key-path forecast
          family_post:
            tasks_post_{{ ec.fhr }}:
              expand:
                fhr: !list '[{% for h in range(0, forecast.aigfs_inference.forecast_length + 1, forecast.aigfs_inference.forecast_freq) %}{{ "f%03d" % h }},{% endfor %} ]'
              trigger: "../jaigfs_forecast:release_{{ ec.fhr }}"
              script:
                <<: *script
                manual: "Runs AIGFS post for {{ ec.fhr }}."
                batchargs: !dict "{{ post.aigfs_post.execution.batchargs }}"
                body: |
                  source %AIGFS_APP%/bin/activate-%PLATFORM%
                  module load wgrib2
                  export FH=%FHR%
                  export INPUTDIR={{ forecast.aigfs_inference.rundir }}
                  %AIGFS_APP%/scripts/post
              vars:
                FHR: "{{ ec.fhr }}"
