app:
  cycle_freq: !timedelta 6
  first_cycle: !datetime 2025-10-21T00
  last_cycle: !datetime 2025-10-21T00
  pretrained_model_path: YOUR_PRETRAINED_MODEL_DIR
  rundir: YOUR_EXPERIMENT_DIR
timevars:
  cyc: '{{ cycle.strftime("%H") }}'
  fff: '{{ "%03d" % (leadtime.total_seconds() // 3600) }}'
  m1_cyc: '{{ (cycle - app.cycle_freq).strftime("%H") }}'
  m1_yyyymmdd: '{{ (cycle - app.cycle_freq).strftime("%Y%m%d") }}'
  m2_cyc: '{{ (cycle - 2*app.cycle_freq).strftime("%H") }}'
  m2_yyyymmdd: '{{ (cycle - 2*app.cycle_freq).strftime("%Y%m%d") }}'
  valid_time: "{{ (cycle + leadtime).strftime('%Y-%m-%d_%H:%M:%S') }}"
  yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
  yyyymmddhh: '{{ cycle.strftime("%Y%m%d%H") }}'
prep:
  aigfs_ics:
    execution:
      batchargs:
        debug: True
        memory: 10GB
        nodes: 1
        rundir: '{{ app.app_home }}'
        tasks_per_node: 1
        walltime: 00:30:00
      envcmds:
        - source {{ app.app_home }}/bin/activate-{{ app.platform }}
        - module load wgrib2
      executable: uw execute --module {{ app.app_home }}/drivers/aigfs_ics.py --classname AIGFSICs --task merged_netcdf_files -c {{ app.rundir }}/experiment.yaml --cycle {{ cycle.strftime('%Y-%m-%d_%H:%M:%S') }} --key-path prep
    files_to_hardlink:
      data/gfs.t{{ timevars.cyc }}z.pgrb2.0p25.f000: '{{ user.gfs_data }}/{{ timevars.yyyymmdd }}/gfs.t{{ timevars.cyc }}z.pgrb2.0p25.f000'
      data/gfs.t{{ timevars.m1_cyc }}z.pgrb2.0p25.f000: '{{ user.gfs_data }}/{{ timevars.m1_yyyymmdd }}/gfs.t{{ timevars.m1_cyc}}z.pgrb2.0p25.f000'
      data/gfs.t{{ timevars.m1_cyc }}z.pgrb2.0p25.f006: '{{ user.gfs_data }}/{{ timevars.m1_yyyymmdd }}/gfs.t{{ timevars.m1_cyc}}z.pgrb2.0p25.f006'
      data/gfs.t{{ timevars.m2_cyc }}z.pgrb2.0p25.f006: '{{ user.gfs_data }}/{{ timevars.m2_yyyymmdd }}/gfs.t{{ timevars.m2_cyc }}z.pgrb2.0p25.f006'
    rundir: '{{ app.rundir }}/{{ cycle.strftime("%Y%m%d%H") }}/prep'
    variable_extraction_yaml: '{{ app.app_home }}/parm/wgrib2_data.yaml'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
forecast:
  aigfs_inference:
    diffs_stddev_path: '{{ app.pretrained_model_path }}/stats/diffs_stddev_by_level.nc'
    execution:
      batchargs:
        debug: True
        memory: 150GB
        nodes: 1
        tasks_per_node: 128
        walltime: 01:30:00
      envcmds:
        - source {{ app.app_home }}/bin/activate-{{ app.platform }}
        - set -x
      executable: uw execute --module {{ app.app_home }}/drivers/aigfs_inference.py --classname AIGFSInference --task predictions -c {{ app.rundir }}/experiment.yaml --cycle {{ cycle.strftime('%Y-%m-%d_%H:%M:%S') }} --key-path forecast
    forecast_freq: 6
    forecast_length: 120
    ics_path: '{{ prep.aigfs_ics.rundir }}/aigfs.t{{ timevars.cyc }}z.ic.nc'
    json_path: '{{ app.pretrained_model_path }}/tables'
    mean_path: '{{ app.pretrained_model_path }}/stats/mean_by_level.nc'
    model_weights_path: '{{ app.pretrained_model_path }}/params/GCGFSv2_finetuned - GDAS - ERA5 - resolution 0.25 - pressure levels 13 - mesh 2to6 - precipitation output only.npz'
    rundir: '{{ app.rundir }}/{{ cycle.strftime("%Y%m%d%H") }}/forecast'
    stddev_path: '{{ app.pretrained_model_path }}/stats/stddev_by_level.nc'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
post:
  aigfs_post:
    execution:
      batchargs:
        debug: True
        memory: 4GB
        nodes: 1
        tasks_per_node: 1
        walltime: 00:05:00
      envcmds:
        - source {{ app.app_home }}/bin/activate-{{ app.platform }}
        - module load wgrib2
      executable: uw execute --module {{ app.app_home }}/drivers/aigfs_post.py --classname AIGFSPost --task delivery -c {{ app.rundir }}/experiment.yaml --cycle {{ cycle.strftime('%Y-%m-%d_%H:%M:%S') }} --key-path post --leadtime $FHR
    deliver_to: "{{ forecast.aigfs_inference.rundir }}"
    inputfiles:
      - '{{ forecast.aigfs_inference.rundir }}/aigfs.t{{ timevars.cyc }}z.sfc.f{{ timevars.fff }}.grib2'
      - '{{ forecast.aigfs_inference.rundir }}/aigfs.t{{ timevars.cyc }}z.pres.f{{ timevars.fff }}.grib2'
    outputdir: '{{ post.aigfs_post.rundir }}'
    rundir: '{{ app.rundir }}/{{ timevars.yyyymmddhh }}/post_{{ timevars.fff }}'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
user:
  gfs_data: YOUR_GFS_DATA
