---
- name: Create rtaigfs install directory
  ansible.builtin.file:
    path: "{{ rtaigfs_install_dir | realpath }}"
    state: directory
    mode: "0755"

- name: Install rtaigfs launcher
  ansible.builtin.copy:
    src: rtaigfs
    dest: "{{ rtaigfs_install_dir | realpath }}/rtaigfs"
    mode: "0755"

- name: Install rtaigfs configuration
  ansible.builtin.copy:
    src: rtaigfs.yaml
    dest: "{{ rtaigfs_install_dir | realpath }}/rtaigfs.yaml"
    mode: "0644"

- name: Extract rtaigfs model archive
  ansible.builtin.unarchive:
    src: "{{ rtaigfs_model_archive_path }}"
    dest: "{{ rtaigfs_install_dir | realpath }}"
    remote_src: true
    creates: "{{ rtaigfs_install_dir | realpath }}/model"
