---
rtaigfs_bb_arch: "{{ {'x86_64': 'amd64', 'aarch64': 'aarch64'}[ansible_facts['architecture']] }}"
rtaigfs_bb_url: https://github.com/babashka/babashka/releases/download/v{{ rtaigfs_bb_version }}/babashka-{{ rtaigfs_bb_version }}-linux-{{ rtaigfs_bb_arch }}-static.tar.gz
rtaigfs_bb_version: 1.13.225
rtaigfs_bin_dir: "{{ rtaigfs_install_dir | realpath }}/bin"
rtaigfs_crontab_path: "{{ rtaigfs_install_dir | realpath }}/crontab"
rtaigfs_crontab_path_env: "{{ rtaigfs_bin_dir }}:/usr/local/bin:/usr/bin:/bin"
rtaigfs_install_dir: "{{ playbook_dir }}/../../../app"
rtaigfs_model_archive: aigfs-v1.1.tgz
rtaigfs_model_archive_path: "/home/{{ rtaigfs_user }}/models/{{ rtaigfs_model_archive }}"
rtaigfs_user: role.rtaigfs
