user:
  experiment_dir: /scratch3/BMC/wrfruc/cholt/aigfs/run3
  aigfs_app: /scratch3/BMC/wrfruc/cholt/aigfs/aigfs/
  gfs_data: /scratch3/BMC/wrfruc/cholt/aigfs/sample_data
  cycle_freq: !timedelta 6
  first_cycle: !datetime 2025-10-21T00
  last_cycle: !datetime 2025-10-21T00
  platform: ursa
platform:
  account: zrtrr
  pretrained_model_path: /scratch3/BMC/wrfruc/cholt/aigfs/fix/gc_weights
  scheduler: slurm
timevars:
  valid_time: "{{ (cycle + leadtime).strftime('%Y-%m-%d_%H:%M:%S') }}"
  yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
  yyyymmddhh: '{{ cycle.strftime("%Y%m%d%H") }}'
  cyc: '{{ cycle.strftime("%H") }}'
  fff: '{{ "%03d" % (leadtime.total_seconds() // 3600) }}'
  m2_cyc: '{{ (cycle - 2*user.cycle_freq).strftime("%H") }}'
  m2_yyyymmdd: '{{ (cycle - 2*user.cycle_freq).strftime("%Y%m%d") }}'
  m1_cyc: '{{ (cycle - user.cycle_freq).strftime("%H") }}'
  m1_yyyymmdd: '{{ (cycle - user.cycle_freq).strftime("%Y%m%d") }}'
prep:
  aigfs_ics:
    execution:
      batchargs:
        debug: True
        memory: 10GB
        nodes: 1
        tasks_per_node: 1
        walltime: 00:30:00
        rundir: '{{ user.aigfs_app }}'
      jobcmd: uw execute --module drivers/generate_ics.py --classname GenICS --task run -c {{ user.experiment_dir }}/config.yaml --cycle {{ cycle.strftime('%Y-%m-%d_%H:%M:%S') }} --key-path prep
      envcmds:
        - source /scratch3/BMC/wrfruc/cholt/aigfs/etc/profile.d/conda.sh
        - conda activate aigfs
        - module load wgrib2
      executable: uw execute --module drivers/generate_ics.py --classname GenICS --task provisioned_rundir -c {{ user.experiment_dir }}/config.yaml --cycle {{ cycle.strftime('%Y-%m-%d_%H:%M:%S') }} --key-path prep
    files_to_hardlink:
      data/gfs.t{{ timevars.m2_cyc }}z.pgrb2.0p25.f006: '{{ user.gfs_data }}/{{ timevars.m2_yyyymmdd }}/gfs.t{{ timevars.m2_cyc }}z.pgrb2.0p25.f006'
      data/gfs.t{{ timevars.m1_cyc }}z.pgrb2.0p25.f000: '{{ user.gfs_data }}/{{ timevars.m1_yyyymmdd }}/gfs.t{{ timevars.m1_cyc}}z.pgrb2.0p25.f000'
      data/gfs.t{{ timevars.m1_cyc }}z.pgrb2.0p25.f006: '{{ user.gfs_data }}/{{ timevars.m1_yyyymmdd }}/gfs.t{{ timevars.m1_cyc}}z.pgrb2.0p25.f006'
      data/gfs.t{{ timevars.cyc }}z.pgrb2.0p25.f000: '{{ user.gfs_data }}/{{ timevars.yyyymmdd }}/gfs.t{{ timevars.cyc }}z.pgrb2.0p25.f000'
    rundir: '{{ user.experiment_dir }}/{{ cycle.strftime("%Y%m%d%H") }}/prep'
    variable_extraction_yaml: '{{ user.aigfs_app }}/parm/wgrib2_data_to_process.yml'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
forecast:
  graphcast_model:
    execution:
      batchargs:
        debug: True
        memory: 150GB
        nodes: 1
        tasks_per_node: 128
        walltime: 01:30:00
      jobcmd: "run graphcast"
      envcmds:
        - source /scratch3/BMC/wrfruc/cholt/aigfs/etc/profile.d/conda.sh
        - conda activate aigfs
      executable: uw execute --module drivers/run_graphcast.py --classname GraphCastModel --task predictions -c {{ user.experiment_dir }}/config.yaml --cycle {{ cycle }} --key-path forecast
    forecast_freq: 6
    forecast_length: 120
    ics_path: '{{ prep.aigfs_ics.rundir }}/aigfs.t{{ timevars.cyc }}z.ic.nc'
    json_path: '{{ platform.pretrained_model_path }}/tables'
    diffs_stddev_path: '{{ platform.pretrained_model_path }}/stats/diffs_stddev_by_level.nc'
    model_weights_path: '{{ platform.pretrained_model_path }}/params/GCGFSv2_finetuned - GDAS - ERA5 - resolution 0.25 - pressure levels 13 - mesh 2to6 - precipitation output only.npz'
    mean_path: '{{ platform.pretrained_model_path }}/stats/mean_by_level.nc'
    stddev_path: '{{ platform.pretrained_model_path }}/stats/stddev_by_level.nc'
    rundir: '{{ user.experiment_dir }}/{{ cycle.strftime("%Y%m%d%H") }}/forecast'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
post:
  aigfs_post:
    execution:
      batchargs:
        debug: True
        memory: 4GB
        nodes: 1
        tasks_per_node: 1
        walltime: 00:05:00
      envcmds:
        - module load wgrib2
      jobcmd: oh hi job
      executable: hello world
    rundir: '{{ user.experiment_dir }}/{{ cycle.strftime("%Y%m%d%H") }}/post_{{ timevars.fff }}'
  platform:
    account: '{{ platform.account }}'
    scheduler: '{{ platform.scheduler }}'
