name: Build and Publish API Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Build and Publish API Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - name: Prepare Environment
        run: make devenv
      - name: Build API Docs
        run: make docs
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/api/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
